### ISSUE TITLE
Gecko's IsServiceUp function does not check if dependencies are up

### ISSUE THREAD

**Issue by aaronbuchwald** [kurtosis-tech/ava-e2e-tests#94]
IsServiceUp parameters indicate that the dependencies should be checked to see if they are up before beginning to check if the toCheck service is up: https://github.com/kurtosis-tech/ava-e2e-tests/blob/develop/commons/ava_services/gecko_service_availability_checker_core.go#L12

This may require a change to the Service interface since a service may depend on another service, it would be helpful to be able to call IsServiceUp on a single service, so that the current IsServiceUp function can verify that its dependencies are up before checking to see if the service itself is up.

**Comment by mieubrisse** [comment]
Hey @aaronbuchwald , so this is actually intentional - the Gecko nodes won't report themselves as bootstrapped until after their bootstrap nodes are up, so a node being up implicitly implies that its bootstrappers up. I'll add a comment to the code to clarify this!

At a broader level, Kurtosis provides the dependencies as part of the `IsServiceUp` because if you had a service that, unlike Gecko, might report itself as "up" even if its dependencies weren't, you might need to check the dependencies to make sure they're also up before declaring the service ready for use.

**Comment by mieubrisse** [comment]
https://github.com/kurtosis-tech/ava-e2e-tests/pull/98 too

**Comment by mieubrisse** [comment]
Hey @aaronbuchwald , can we close this - does the above make sense?

**Comment by aaronbuchwald** [comment]
Yup makes complete sense
